name: attendance_application
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  wakelock: ^0.1.4+1
  audioplayers: ^0.15.0
  firebase_auth: ^0.15.5+3
  google_sign_in: ^4.4.1
  flutter_secure_storage: ^3.3.1+1
  flutter_launcher_icons: ^0.7.4
  provider: ^4.0.4
  bottom_navy_bar: ^5.3.2
  qrscan: ^0.2.17
  dio: ^3.0.9
  sqflite: ^1.2.2+1
  path: ^1.6.4
  uuid: ^2.0.4
  flutter_bloc: ^3.2.0
  sqfentity: ^1.3.2
  sqfentity_gen: ^1.3.2+1
  socket_io_client: ^0.9.9
  flutter_socket_io: ^0.6.0
  flutter_simple_dependency_injection: ^1.0.2+1
  intl: ^0.16.1
  line_icons: ^0.2.0
  fluttertoast: ^4.0.1
  geolocator: ^5.3.1
  google_nav_bar: ^2.1.0
  latlong: ^0.6.1
  location: ^3.0.2
  slide_digital_clock: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/audio/chunchun.mp3
    - assets/audio/oof.mp3
    - assets/audio/beep_short.mp3
    - assets/audio/beep_warn.mp3
    - assets/
    - assets/img/
    - assets/img/background/
    - assets/img/background/uhf_icon.png
    - assets/img/icons/
    - assets/img/icons/icon-logo.png
    - assets/img/icons/google_logo.png
    - assets/img/icons/icon-profile.png
    - assets/img/background/background-profile.jpg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 600
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 400
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/img/icons/icon-logo.png'